server:
  forward-headers-strategy: framework

spring:
  application:
    name: sopt-linkareer

  datasource:
    url: jdbc:mysql://{DB_URL}:3306/sopt_linkareer
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
  default-consume-media-type: application/json
  default-produce-media-type: application/json
